[package]
name = "typeinfer"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "typeinfer"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.21.1"

[profile.release]
debug = 1
